### ISSUE TITLE
atom 1.1.0 language-babel install problem

### ISSUE THREAD

**Issue by universalien** [gandm/language-babel#101]
Atom 1.1.0 on Windows 8.1

Installing “language-babel@1.0.0” failed.Hide output…

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EPERM, open 'C:\Users\LOKALH~1\AppData\Local\Temp\apm-install-dir-115103-8976-19r1aoh\node_modules\language-babel\node_modules\babel-core\node_modules\babel-runtime\node_modules\core-js\modules\core.log.js'

Cannot find module 'underscore-plus'
Hide Stack Trace
Error: Cannot find module 'underscore-plus'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\lokalhorst\.atom\packages\language-babel\node_modules\fs-plus\lib\fs-plus.js:11:7)
  at Object.<anonymous> (C:\Users\lokalhorst\.atom\packages\language-babel\node_modules\fs-plus\lib\fs-plus.js:646:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\lokalhorst\.atom\packages\language-babel\lib\transpiler.coffee:1:6)
  at Object.<anonymous> (C:\Users\lokalhorst\.atom\packages\language-babel\lib\transpiler.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.activate (C:\Users\lokalhorst\.atom\packages\language-babel\lib\main.coffee:7:25)
  at Package.module.exports.Package.activateNow (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:232:19)
  at C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:212:32
  at Package.module.exports.Package.measure (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:153:15)
  at C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:205:26
  at Package.module.exports.Package.activate (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:201:34)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:474:21)
  at C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:310:19
  at C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:568:20
  at Emitter.module.exports.Emitter.emit (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at Config.module.exports.Config.emitChangeEvent (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:753:29)
  at Config.module.exports.Config.setRawValue (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:545:19)
  at Config.module.exports.Config.set (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:215:14)
  at Config.module.exports.Config.removeAtKeyPath (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:332:12)
  at Package.module.exports.Package.enable (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:138:26)
  at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:139:14)
  at HTMLButtonElement.<anonymous> (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:314:27)
  at HTMLButtonElement.jQuery.event.dispatch (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

**Comment by gandm** [comment]
Looks llke an apm/atom issue


Sent from my Windows Phone
________________________________

**Comment by gandm** [comment]
I suggest you try and install the package again. Stop and restart atom and see if that fixes it.

**Comment by gandm** [comment]
Closing. Reopen if still and issue.
