### ISSUE TITLE
Failed to activate language-babel package

### ISSUE THREAD

**Issue by jtsom** [gandm/language-babel#102]
(Using Atom 1.2.0-beta1)

When launching, an error is shown:

[Enter steps to reproduce below:]

1. Launch Atom

**Atom Version**: 1.2.0-beta1
**System**: Mac OS X 10.11.1
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package, v2.0.0

### Stack Trace

Failed to activate the language-babel package

```
At Cannot find module './transformer-task'

Error: Cannot find module './transformer-task'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (module.js:388:19)
    at new Transpiler (/Users/John/.atom/packages/language-babel/lib/transpiler.coffee:28:37)
    at Object.module.exports.activate (/Users/John/.atom/packages/language-babel/lib/main.coffee:7:20)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:140:34)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "customFileTypes": {
      "source.js": [
        ".js"
      ],
      "source": [
        "[object Object]"
      ]
    }
  },
  "language-babel": {
    "transpileOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v1.2.0
ember-snippets, v1.4.0
emmet, v2.3.14
file-icons, v1.6.11
language-babel, v2.0.0
language-swift, v0.4.0
open-recent, v4.0.1

# Dev
No dev packages
```

**Comment by callmewhy** [comment]
same error...babel6

**Comment by jtsom** [comment]
Looks like he's on it, and a new update is available :)

**Comment by callmewhy** [comment]
fixed :+1:

**Comment by gandm** [comment]
Yes my git screwed up!!! 2.0.2 should be OK.
