### ISSUE TITLE
Uncaught Error: Cannot find module 'C:\Users\dshm\.atom\packages\language-babel\lib\transformer-t...

### ISSUE THREAD

**Issue by dshm** [gandm/language-babel#109]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package, v2.4.1

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\dshm\.atom\packages\language-babel\lib\transformer-task.coffee'

```
At C:\Users\dshm\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:788

Error: Cannot find module 'C:\Users\dshm\.atom\packages\language-babel\lib\transformer-task.coffee'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\dshm\AppData\Local\atom\app-1.1.0\resources\app.asar\src\module-cache.js:383:52)
  at Function.require.resolve (module.js:386:19)
  at new Task (C:\Users\dshm\AppData\Local\atom\app-1.1.0\resources\app.asar\src\task.js:35:26)
  at Function.module.exports.Task.once (C:\Users\dshm\AppData\Local\atom\app-1.1.0\resources\app.asar\src\task.js:17:14)
  at Transpiler.transpile (C:\Users\dshm\.atom\packages\language-babel\lib\transpiler.coffee:69:12)
  at C:\Users\dshm\.atom\packages\language-babel\lib\main.coffee:16:21
  at Emitter.module.exports.Emitter.emit (C:\Users\dshm\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\dshm\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1035:20)
  at TextBuffer.module.exports.TextBuffer.save (C:\Users\dshm\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1002:19)
  at TextEditor.module.exports.TextEditor.save (C:\Users\dshm\AppData\Local\atom\app-1.1.0\resources\app.asar\src\text-editor.js:519:26)
  at Pane.module.exports.Pane.saveItem (C:\Users\dshm\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:529:18)
  at Pane.module.exports.Pane.saveActiveItem (C:\Users\dshm\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:512:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\dshm\AppData\Local\atom\app-1.1.0\resources\app.asar\src\workspace.js:560:35)
  at atom-workspace.atom.commands.add.core:save (C:\Users\dshm\AppData\Local\atom\app-1.1.0\resources\app.asar\src\workspace-element.js:270:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\dshm\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:243:29)
  at C:\Users\dshm\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\dshm\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\dshm\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\dshm\AppData\Local\atom\app-1.1.0\resources\app.asar\src\window-event-handler.js:97:20)

```

### Commands

```
  2x -1:32.8.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:20.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:03.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "language-babel": {
    "createTranspiledCode": true,
    "transpileOnSave": true,
    "allowLocalOverride": true,
    "createTargetDirectories": false,
    "suppressSourcePathMessages": false,
    "babelMapsAddUrl": false
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
atom-beautify, v0.28.17
autocomplete-plus, v2.23.0
autocomplete-snippets, v1.8.0
color-picker, v2.0.13
emmet, v2.3.14
file-icons, v1.6.11
javascript-snippets, v1.0.0
jquery-snippets, v11.0.0
language-babel, v2.4.1
linter, v1.10.0
linter-csslint, v1.1.0
linter-eslint, v4.0.0
minimap, v4.16.0
react, v0.12.10
Remote-FTP, v0.7.10
symbols-tree-view, v0.10.1

# Dev
No dev packages
```

**Comment by dshm** [comment]
fixed after restart atom
