### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by sheeley** [gandm/language-babel#113]
[Enter steps to reproduce below:]

1. Create file with these contents: 
```
const Something = {

  isExperiment: {
    type:
}
```
2. Save/lint

**Atom Version**: 1.3.0-beta6
**System**: Mac OS X 10.11.1
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package, v2.5.3

### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/src/display-buffer.js:790

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/display-buffer.js:790:15)
    at TextEditorMarker.module.exports.TextEditorMarker.getHeadScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-marker.js:179:33)
    at Cursor.module.exports.Cursor.getScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/cursor.js:71:26)
    at Cursor.module.exports.Cursor.getScreenRange (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/cursor.js:686:20)
    at Cursor.module.exports.Cursor.autoscroll (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/cursor.js:691:51)
    at Cursor.module.exports.Cursor.changePosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/cursor.js:676:21)
    at Cursor.module.exports.Cursor.setBufferPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/cursor.js:78:19)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1401:23
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1638:9)
    at TextEditor.module.exports.TextEditor.setCursorBufferPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1400:19)
    at /Users/jsheeley/.atom/packages/language-babel/lib/transpiler.coffee:106:26
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/task.js:136:25
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/task.js:126:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at ChildProcess.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/task.js:78:34)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

### Commands

```
  2x -0:15.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:11.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:11.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:11.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:11.2.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:11 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:11 snippets:expand (atom-text-editor.editor.is-focused)
     -0:11 editor:indent (atom-text-editor.editor.is-focused)
     -0:07.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:07.1.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:02.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:02.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:02.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:02.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:01.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:00.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "solarized-seti-ui",
      "monokai-seti"
    ],
    "ignoredNames": [
      "node_modules/*",
      "bower_components/*"
    ],
    "disabledPackages": [
      "jscs-fixer",
      "react",
      "standard-formatter",
      "linter-js-standard",
      "autocomplete-paths"
    ]
  },
  "language-babel": {
    "disableWhenNoBabelrcFileInPath": true,
    "babelTranspilePath": "dist",
    "transpileOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-minify, v0.6.2
auto-detect-indentation, v0.4.2
auto-indent, v0.5.0
autocomplete-python, v0.10.7
close-after-last-tab, v0.1.6
highlight-selected, v0.11.1
jsonlint, v1.1.2
language-babel, v2.5.3
language-gitignore, v0.2.0
language-gradle, v0.0.3
language-terraform, v0.6.0
linter, v1.11.3
linter-coffeescript, v1.0.0
linter-eslint, v5.2.4
linter-jsonlint, v1.1.0
monokai-seti, v0.7.0
package-manager-commands, v2.0.3
pigments, v0.19.1
pretty-json, v0.4.1
set-syntax, v0.3.0
solarized-seti-ui, v0.8.6
sync-settings, v0.6.0
synced-sidebar, v0.4.3
tag, v0.3.0

# Dev
No dev packages
```

**Comment by sheeley** [comment]
Actually, the editor destroyed appears to happen when saving any file with syntax errors.

**Comment by gandm** [comment]
Um. I can't recreate on Windows 10 using Atom 1.2.4. I also tried with Atom 1.3.0-beta6 (yellow atom icon in image below) and it works for me with babel-eslint enabled.
![image](https://cloud.githubusercontent.com/assets/2313237/11564590/e604e3a2-99d1-11e5-9a83-f45029a85a78.png)
I'm just asking the TextEditor to position the cursor at the error position row/col.

Is the file still visible in Atom after the save?

**Comment by gandm** [comment]
Also tried with lastest version of babel-core
![image](https://cloud.githubusercontent.com/assets/2313237/11565292/31fe8242-99d5-11e5-8528-00e9ad7470a3.png)

**Comment by gandm** [comment]
Can you see if 2.5.4 makes things better. Babel seems to return a row number indexed from 1 but a column number indexed from 0.

**Comment by sheeley** [comment]
This went away with 2.5.3 - sorry to have wasted your time!

**Comment by gandm** [comment]
Not a waste of time as 2.5.4 did fix a Babel core indexing issue. I guess this was the root cause of your problem,

**Comment by sheeley** [comment]
Seeing this again

[Enter steps to reproduce below:]

Using code like this (obviously wrong, but that shouldn't crash the editor, should it?):
```js
import React from 'react'

const Menu = React.createClass({
  propTypes: {

  },
  getInitialState() {
    return {

    }
  },


  render() {

    return (
      <section>
      </section>
    )
  }
}

export default Menu
```

**Atom Version**: 1.3.0-beta6
**System**: Mac OS X 10.11.1
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package, v2.6.0


### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/src/display-buffer.js:790

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/display-buffer.js:790:15)
    at TextEditorMarker.module.exports.TextEditorMarker.getHeadScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-marker.js:179:33)
    at Cursor.module.exports.Cursor.getScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/cursor.js:71:26)
    at Cursor.module.exports.Cursor.getScreenRange (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/cursor.js:686:20)
    at Cursor.module.exports.Cursor.autoscroll (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/cursor.js:691:51)
    at Cursor.module.exports.Cursor.changePosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/cursor.js:676:21)
    at Cursor.module.exports.Cursor.setBufferPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/cursor.js:78:19)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1401:23
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1638:9)
    at TextEditor.module.exports.TextEditor.setCursorBufferPosition (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1400:19)
    at /Users/jsheeley/.atom/packages/language-babel/lib/transpiler.coffee:106:26
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/task.js:136:25
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/task.js:126:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at ChildProcess.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/task.js:78:34)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

### Commands

```
     -0:32.5.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:32 core:move-up (atom-text-editor.editor.is-focused)
     -0:31.6.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -0:31.3.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:30.7.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:30.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:29.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:28.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:27 core:save (atom-text-editor.editor.is-focused)
  2x -0:21.2.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:18.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:14.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:14.6.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:14.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:09.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:09.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "solarized-seti-ui",
      "monokai-seti"
    ],
    "ignoredNames": [
      "node_modules/*",
      "bower_components/*"
    ],
    "disabledPackages": [
      "jscs-fixer",
      "react",
      "standard-formatter",
      "linter-js-standard",
      "autocomplete-paths"
    ]
  },
  "language-babel": {
    "disableWhenNoBabelrcFileInPath": true,
    "babelTranspilePath": "dist",
    "transpileOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-minify, v0.6.2
auto-detect-indentation, v0.4.2
auto-indent, v0.5.0
autocomplete-python, v1.2.2
close-after-last-tab, v0.1.6
highlight-selected, v0.11.1
jsonlint, v1.1.2
language-babel, v2.6.0
language-gitignore, v0.2.0
language-gradle, v0.0.3
language-sql-mysql, v0.3.1
language-terraform, v0.6.0
linter, v1.11.3
linter-coffeescript, v1.0.0
linter-eslint, v5.2.6
linter-jsonlint, v1.1.0
linter-xo, v0.10.3
monokai-seti, v0.7.0
package-manager-commands, v2.0.3
pigments, v0.19.1
pretty-json, v0.4.1
set-syntax, v0.3.0
solarized-seti-ui, v0.8.6
sync-settings, v0.6.0
synced-sidebar, v0.4.3
tag, v0.3.0

# Dev
No dev packages
```

**Comment by gandm** [comment]
Well the above code works for me. Seems like an Atom issue that raises it's head occasionally. See https://github.com/atom/atom/issues/4562 

Is it reproducible? Any console messages?

**Comment by gandm** [comment]
OK. I've managed to recreate this but only when a split screen on the file in question. Destroying one of the file's tab sand saving on the remaining tab gets the error. I'll look at fixing this soon,

Would this describe your problem?

**Comment by sheeley** [comment]
Ah, interesting - that may have been the cause. It's no longer happening for me. I don't believe I saw anything in the console other than the trace info I included above - if it happens again, I'll try to actually track down and solve. :)

**Comment by gandm** [comment]
@sheeley v2.6.1. should fix the TextEditor has been destroyed issues.

**Comment by cristian-sima** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package, v2.28.0


### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\display-buffer.js:794

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\display-buffer.js:794:15)
    at TextEditorMarker.module.exports.TextEditorMarker.getHeadScreenPosition (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor-marker.js:179:33)
    at Cursor.module.exports.Cursor.getScreenPosition (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\cursor.js:73:26)
    at Cursor.module.exports.Cursor.getScreenRange (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\cursor.js:685:20)
    at Cursor.module.exports.Cursor.autoscroll (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\cursor.js:690:51)
    at Cursor.module.exports.Cursor.changePosition (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\cursor.js:675:21)
    at Cursor.module.exports.Cursor.setBufferPosition (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\cursor.js:80:19)
    at C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:1527:23
    at TextEditor.module.exports.TextEditor.moveCursors (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:1780:9)
    at TextEditor.module.exports.TextEditor.setCursorBufferPosition (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:1526:19)
    at file:///C:/Users/Cristian/.atom/packages/language-babel/lib/transpiler.coffee:182:26
    at C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\task.js:136:25
    at C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\task.js:126:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at ChildProcess.<anonymous> (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\task.js:78:34)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

### Commands

```
     -0:45.9.0 core:move-down (atom-text-editor.editor.is-focused)
  5x -0:33.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:27.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:24.9.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:24.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:22.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:22.3.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:22.3.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:20 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:11.1.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:10.6.0 core:save (atom-text-editor.editor.mini.is-focused)
     -0:09.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:09.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:08.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.2.0 core:close (atom-text-editor.editor.is-focused)
     -0:05.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "spell-check",
      "language-csharp",
      "language-c",
      "language-ruby",
      "language-python",
      "language-ruby-on-rails",
      "atom-minify",
      "linter-jshint",
      "environment",
      "css-clean",
      "tester-go",
      "atom-ternjs",
      "source-preview-babel",
      "source-preview",
      "linter-csslint",
      "linter-eslint"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "staticp"
    ],
    "packagesWithKeymapsDisabled": [
      "spell-check",
      "markdown-preview-plus",
      "atom-minify",
      "highlight-line",
      "tree-view",
      "linter",
      "linter-sass-lint"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "language-babel": {
    "allowLocalOverride": true,
    "transpileOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
auto-indent, v0.5.0
autocomplete-go, v1.1.0
autoupdate-packages, v1.3.1
builder-go, v1.0.0
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.15
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
highlight-selected, v0.11.2
language-babel, v2.28.0
linter, v1.11.14
linter-sass-lint, v1.6.1
markdown-preview-plus, v2.4.0
multi-cursor, v2.1.3
navigator-godef, v1.0.3
pigments, v0.29.2
react, v0.15.0
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by gandm** [comment]
@cristian-sima I can't recreate. Can you make this reproducible?

**Comment by gandm** [comment]
@cristian-sima I think I can see what may be happening. Please download 2.29.0 and hopefully you won't get that issue again.

**Comment by cristian-sima** [comment]
I do not know what I've done, but probably I closed the tab that was been traspiled
