### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by rasheedhamdawi** [gandm/language-babel#126]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package, v2.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:810

TypeError: Cannot read property 'match' of undefined
    at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:674:23)
    at DisplayBuffer.module.exports.DisplayBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:596:35)
    at TextEditor.module.exports.TextEditor.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2338:33)
    at TextEditor.module.exports.TextEditor.indentationForBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2310:19)
    at AutoIndent.module.exports.AutoIndent.formatJSX (~/.atom/packages/language-babel/lib/auto-indent.coffee:259:36)
    at AutoIndent.module.exports.AutoIndent.autoIndentBufferRow (~/.atom/packages/language-babel/lib/auto-indent.coffee:71:15)
    at LanguageMode.autoIndentBufferRow (~/.atom/packages/language-babel/lib/auto-indent.coffee:1:1)
    at TextEditor.module.exports.TextEditor.autoIndentBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:3068:32)
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:498:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:777:29
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:816:29
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1216:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:810:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2096:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2058:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:808:19)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:774:19)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditor.module.exports.TextEditor.insertNewline (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:789:19)
    at TextEditor.object.(anonymous function) [as insertNewline] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditor.commandRegistry.add.stopEventPropagationAndGroupUndo.editor:newline (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:519:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:573:34
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1216:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:572:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -0:01.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.9.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "material-ui",
      "material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.6.13
language-babel, v2.8.0
material-syntax, v0.5.0
material-ui, v1.0.5
tool-bar, v0.1.10
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by gandm** [comment]
I can't recreate this. Is it reproducible? I've just published 2.8.1 that initializes some variables prior to use which may help.

**Comment by tschaub** [comment]
I'm using `language-babel@2.8.1` and seeing the same.  This is fairly severe as it keeps the editor from working (for example, I cannot type a function body in `function() {}`).

**Comment by mpaarating** [comment]
I've had the same issue:

1. npm install
2. type in a file `import Alt from 'alt';`

**Atom Version**: 1.3.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package, v2.8.1


### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:803

TypeError: Cannot read property 'match' of undefined
    at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForLine (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\tokenized-buffer.js:669:23)
    at DisplayBuffer.module.exports.DisplayBuffer.indentLevelForLine (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\display-buffer.js:596:35)
    at TextEditor.module.exports.TextEditor.indentLevelForLine (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\text-editor.js:2338:33)
    at TextEditor.module.exports.TextEditor.indentationForBufferRow (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\text-editor.js:2310:19)
    at AutoIndent.module.exports.AutoIndent.formatJSX (file:///C:/Users/alex/.atom/packages/language-babel/lib/auto-indent.coffee:260:36)
    at AutoIndent.module.exports.AutoIndent.autoIndentBufferRow (file:///C:/Users/alex/.atom/packages/language-babel/lib/auto-indent.coffee:71:15)
    at LanguageMode.autoIndentBufferRow (file:///C:/Users/alex/.atom/packages/language-babel/lib/auto-indent.coffee:1:1)
    at TextEditor.module.exports.TextEditor.autoIndentBufferRow (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\text-editor.js:3068:32)
    at Selection.module.exports.Selection.insertText (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\selection.js:498:21)
    at C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\text-editor.js:777:29
    at C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\text-editor.js:816:29
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:798:18)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\text-editor.js:1216:26)
    at C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\text-editor.js:810:24
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\text-editor.js:2092:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\text-editor.js:2058:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\text-editor.js:808:19)
    at TextEditor.module.exports.TextEditor.insertText (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\text-editor.js:774:19)
    at TextEditor.object.(anonymous function) [as insertText] (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:77:27)
    at TextEditor.module.exports.TextEditor.insertNewline (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\text-editor.js:789:19)
    at TextEditor.object.(anonymous function) [as insertNewline] (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:77:27)
    at TextEditor.commandRegistry.add.stopEventPropagationAndGroupUndo.editor:newline (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\register-default-commands.js:519:21)
    at C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\register-default-commands.js:573:34
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:798:18)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\text-editor.js:1216:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\register-default-commands.js:572:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\alex\AppData\Local\atom\app-1.3.3\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -7:06.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -7:04.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -7:04.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -7:04.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -7:04.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -7:04.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -7:04.1.0 editor:newline (atom-text-editor.editor.is-focused)
  6x -7:03.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:01.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -7:01.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:06.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:06.5.0 editor:newline (atom-text-editor.editor.is-focused)
  6x -1:41.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:32.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:02.6.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
emmet, v2.3.17
file-icons, v1.6.13
highlight-selected, v0.11.1
language-babel, v2.8.1
linter, v1.11.3
linter-eslint, v5.2.7
minimap, v4.19.0
react, v0.12.10

# Dev
No dev packages
```

**Comment by gandm** [comment]
Can you try 2.8.2? If it doesn't work or if it works let me know. You can unblock by setting the package setting to disable format JSX.

**Comment by gandm** [comment]
@mpaarating Ah!! I thinkl the package React also monkey patches the Atom code to do auto indentation - as do I. Can you disable that and see if it helps?

**Comment by mpaarating** [comment]
@gandm Turning off Auto Indentation fixed it!

**Comment by gandm** [comment]
@mpaarating turning it off in language-babel or react fixed it?

**Comment by mpaarating** [comment]
@gandm Turning it off in react, I didn't try language-babel. I did upgrade to 2.8.2 as well though. (Although the upgrade alone didn't fix the issue).

**Comment by hidace** [comment]
Yes, turning off auto-indent in the React package solved this for me too.

**Comment by dsifford** [comment]
Tried disabling autoindent in the react package as well as JSX formatting in this package. Still getting errors preventing me from writing. 

To your knowledge, is the nuclide package also conflicting with the auto-indentation of this package?

**Comment by gandm** [comment]
@dsifford I don't use the nuclide package so I can't say. What are the errors?

**Comment by hidace** [comment]
@dsifford I just installed the latest nuclide package (0.111.0) yesterday. I only had to turn off auto-indent  in the React package, didn't touch the nuclide settings.

**Comment by dsifford** [comment]
@hidace hmmm.. strange. Thanks for the info nevertheless!

**Comment by hidace** [comment]
@dsifford Yeah. Actually, come to think of it - when I first had the error, I went and un-installed language-babel. There was a setting in the nuclide package that asked if I wanted to install recommended packages on startup. I checked it and re-started atom. Upon start-up, it installed a few more packages including the latest language-babel. After this is when I went into the React package an had to un-check auto-indentation - so maybe the issue was having an old version of language-babel and it just needed to install the latest version (might have been months since I originally installed it).

**Comment by Syynth** [comment]
I'm also having this issue on 2.8.3 (Atom 1.4.0, Windows 10) with every non-core plugin disabled, even when disabling auto-indent in the `language-babel` package. This does allow me to create empty newlines, but trying to enter in `function() {|}` throws.

**Comment by dsifford** [comment]
@Syynth I did a complete uninstall and reinstall of `language-babel` per @hidace 's recommendation and so far it seems to be working? Might want to give that a shot.

**Comment by Syynth** [comment]
Unfortunately that didn't help either, but I uninstalled and ran `apm install language-babel@2.7.4` to downgrade and things seem to be working again.

**Comment by n-j-m** [comment]
I uninstalled, reinstalled, and disabled all other non-core plugins. The only thing that fixed the issue for me was turning off **Auto Indent** under **Babel ES6 JavaScript Grammar**.

![image](https://cloud.githubusercontent.com/assets/411630/12363556/fb4ef49e-bb8e-11e5-81fc-77d42afbc10b.png)

**Comment by rasheedhamdawi** [comment]
@gandm Thanks, I just updated to 2.8.3, It's work fine now

**Comment by gandm** [comment]
To those of you with problems still, if you turn off the 'format jsx' option in the package settings and restart then that will disable the auto indent/formatting of jsx. No need to turn off auto-indenting as this won't stop the monkey patch.

I still have no idea why some people have this issue. The code only gets activated when a meta.tag.jsx scope is found in a language-babel file. Other code, which is the majority,  just passes through to atom. 

I would uninstall Lang Babel, stop atom, remove any cached code in the atom directory, start up and reinstall and see if that fixes it.

**Comment by IanVS** [comment]
I had this issue in 2.8.2 and upgrading to latest (2.9.2) fixed it.  Thanks!
