### ISSUE TITLE
Uncaught ReferenceError: esLintrcFile is not defined

### ISSUE THREAD

**Issue by skevy** [gandm/language-babel#127]
When I open my project in Atom, I get this error:

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package, v2.8.2

### Stack Trace

Uncaught ReferenceError: esLintrcFile is not defined

```
At /Users/adam/.atom/packages/language-babel/lib/auto-indent.coffee:304

ReferenceError: esLintrcFile is not defined
  at AutoIndent.module.exports.AutoIndent.getEslintrcOptions (/Users/adam/.atom/packages/language-babel/lib/auto-indent.coffee:304:71)
  at new AutoIndent (/Users/adam/.atom/packages/language-babel/lib/auto-indent.coffee:54:8)
  at /Users/adam/.atom/packages/language-babel/lib/main.coffee:28:58
  at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at TextEditor.module.exports.TextEditor.handleGrammarChange (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2784:27)
  at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:187:27)
  at TokenizedBuffer.module.exports.TokenizedBuffer.grammarAddedOrUpdated (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:126:23)
  at /opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:3:61
  at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at GrammarRegistry.module.exports.GrammarRegistry.addGrammar (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar-registry.js:75:20)
  at Grammar.module.exports.Grammar.activate (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar.js:223:48)
  at /opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/package.js:546:25
  at /opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar-registry.js:120:55
  at parseContents (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:119:7)
  at /opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:204:20
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

```

### Commands

```
     -2:35.4.0 pane:show-previous-item (div.panels-item)
     -2:31.1.0 grammar-selector:show (atom-text-editor.editor)
     -2:29.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:29.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:28.3.0 grammar-selector:show (atom-text-editor.editor)
     -2:26.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:26.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:26.5.0 pane:show-next-item (a.inline-block)
  2x -2:23.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "nuclide-debugger-node",
      "nuclide-buck-files",
      "atom-ternjs",
      "linter-flow",
      "nuclide-flow",
      "tree-view",
      "linter"
    ],
    "themes": [
      "one-dark-ui",
      "oceanic-next"
    ]
  },
  "language-babel": {}
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.4.2
auto-update-packages, v1.0.0
autocomplete-modules, v1.3.1
docblockr, v0.7.3
editorconfig, v1.2.2
haskell-grammar, v0.4.0
highlight-selected, v0.11.1
language-docker, v1.1.6
language-dot, v1.6.0
language-gradle, v0.0.3
language-graphql, v0.2.0
language-ini, v1.14.0
language-nginx, v0.6.1
language-ocaml, v1.1.2
language-terraform, v0.6.0
language-thrift, v1.0.2
linter-eslint, v5.2.7
nuclide, v0.111.0
oceanic-next, v0.1.2
open-recent, v4.0.1
pigments, v0.19.6
pretty-json, v0.4.1
symbol-gen, v1.0.0
tool-bar, v0.1.10

# Dev
No dev packages
```

**Comment by gandm** [comment]
OK the line doing the stack trace was trying to tell you that your .eslintrc file has a JSON error. I'll fix this now and roll out 2.8.3

**Comment by skevy** [comment]
Ah. Gotcha. Sorry! Should have taken a closer look before reporting.

Thanks for being so diligent!

**Comment by skevy** [comment]
Yah, it turns out I'm using JSON5 in my eslintrc file, with comments, etc. That's why that's happening.

**Comment by skevy** [comment]
Is there anyway you could support JSON5 here? Since eslint supports it, it would probably be good if this plugin supported it as well.

I'm busy on a project today, but if you'd like a PR for this I'd be happy to take care of it.

**Comment by gandm** [comment]
Yes, it makes sense. I might also read the package.json as well. I'll do it over the weekend sometime. Thanks

**Comment by gandm** [comment]
@skevy JSON5 now supported for `.eslintrc`. I may revisit this sometime and add `.eslintrc` `.eslintrc.json` and .`eslintrc.js` file types & directory recursion.
