### ISSUE TITLE
Uncaught TypeError: Cannot read property 'react/jsx-indent' of undefined

### ISSUE THREAD

**Issue by jasonblanchard** [gandm/language-babel#130]
I was getting this message when opening up atom. After uninstalling the `language-babel` package, I can reproduce it following these steps:

1. Open Atom (no error)
2. Open Settings and got to Install tab
3. Search for `language-babel`
4. Click Install

This message pops up when it finishes installing.

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package, v2.9.1

### Stack Trace

Uncaught TypeError: Cannot read property 'react/jsx-indent' of undefined

```
At /Users/jason/.atom/packages/language-babel/lib/auto-indent.coffee:309

TypeError: Cannot read property 'react/jsx-indent' of undefined
    at AutoIndent.module.exports.AutoIndent.getEslintrcOptions (/Users/jason/.atom/packages/language-babel/lib/auto-indent.coffee:309:29)
    at new AutoIndent (/Users/jason/.atom/packages/language-babel/lib/auto-indent.coffee:55:8)
    at /Users/jason/.atom/packages/language-babel/lib/main.coffee:28:58
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditor.module.exports.TextEditor.handleGrammarChange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2784:27)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:187:27)
    at TokenizedBuffer.module.exports.TokenizedBuffer.grammarAddedOrUpdated (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:126:23)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:3:61
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at GrammarRegistry.module.exports.GrammarRegistry.addGrammar (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar-registry.js:75:20)
    at Grammar.module.exports.Grammar.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar.js:223:48)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:546:25
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar-registry.js:120:55
    at parseContents (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:119:7)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:204:20
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

### Commands

```
     -0:23.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "api-blueprint-preview"
    ]
  },
  "language-babel": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.14
editorconfig, v1.2.2
language-api-blueprint, v1.0.2
linter, v1.11.3
linter-eslint, v5.2.7
linter-htmlhint, v0.3.0
linter-sass-lint, v0.6.3
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by gandm** [comment]
Just repeated your steps but I don't get the error. The error line seems to come from the line that starts to read properties in your .eslintrc file in the root of a project folder. Can you paste a copy of it here?

**Comment by gandm** [comment]
Just pushed 2.9.2 which allows .eslintrc files to have a missing rules section/property. I think this may your problem?

**Comment by jasonblanchard** [comment]
Cool, I think that did it.

Thanks!
