### ISSUE TITLE
Failed to load the language-babel package

### ISSUE THREAD

**Issue by ilkka** [gandm/language-babel#142]
Steps to reproduce:

1. Open Atom
2. Boom

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package, v2.15.3

### Stack Trace

Failed to load the language-babel package

```
At Cannot find module 'fuzzaldrin'

Error: Cannot find module 'fuzzaldrin'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/ilau/.atom/packages/language-babel/lib/auto-complete-jsx.coffee:2:19)
    at Object.<anonymous> (/Users/ilau/.atom/packages/language-babel/lib/auto-complete-jsx.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/ilau/.atom/packages/language-babel/lib/main.coffee:2:19)
    at Object.<anonymous> (/Users/ilau/.atom/packages/language-babel/lib/main.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:722:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:443:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:393:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "proto-repl"
    ],
    "projectHome": "/Users/ilau/src",
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  },
  "language-babel": {}
}
```

### Installed Packages

```coffee
# User
Parinfer, v1.10.0
atom-fix-path, v0.1.0
autoupdate-packages, v1.3.1
clipboard-plus, v0.5.1
disable-keybindings, v0.6.0
editorconfig, v1.2.4
go-plus, v3.5.2
language-ansible, v0.1.3
language-babel, v2.15.3
language-docker, v1.1.6
language-elixir, v0.8.0
language-elm, v1.3.2
linter, v1.11.3
linter-ansible-linting, v1.1.0
linter-elm-make, v0.4.0
linter-eslint, v6.0.0
linter-flow, v4.1.0
linter-golinter, v1.1.0
linter-jscs, v3.4.1
linter-jshint, v1.3.0
linter-jsonlint, v1.1.5
linter-pep257, v0.3.4
linter-pep8, v1.2.1
linter-pylama, v0.2.6
linter-pylint, v1.2.0
pigments, v0.23.1
project-manager, v2.7.6
proto-repl, v0.13.0
python-yapf, v0.9.1
remote-edit, v1.8.24
theme-switcher, v1.1.0

# Dev
No dev packages
```

**Comment by gandm** [comment]
Seems like an issue with the Atom installer. fuzzaldrin is a dependency but ships with core Atom. Try to install language-babel again via apm and see if that works.

**Comment by ilkka** [comment]
That indeed fixed it, thanks a lot :)

**Comment by Karmaliu** [comment]
Proxy is not defined

**Comment by gandm** [comment]
@Karmaliu I don't use a proxy anywhere in my code. I suggest it an atom installer issue. I just pushed a new version maybe this was being updated whilst you were using the system.

**Comment by Karmaliu** [comment]
Update the Atom? My English is not very good. @gandm
