### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by girvo** [gandm/language-babel#144]
```
/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:810
Hide Stack Trace
TypeError: Cannot read property 'name' of undefined
  at AutoIndent.module.exports.AutoIndent.indentJSX (/Users/josh/.atom/packages/language-babel/lib/auto-indent.coffee:309:47)
  at /Users/josh/.atom/packages/language-babel/lib/auto-indent.coffee:107:8
  at TextBuffer.module.exports.TextBuffer.transact (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
  at TextEditor.module.exports.TextEditor.transact (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1244:26)
  at AutoIndent.module.exports.AutoIndent.changedCursorPosition (/Users/josh/.atom/packages/language-babel/lib/auto-indent.coffee:106:13)
  at AutoIndent.changedCursorPosition (/Users/josh/.atom/packages/language-babel/lib/auto-indent.coffee:1:1)
  at /Users/josh/.atom/packages/language-babel/lib/auto-indent.coffee:58:68
  at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at TextEditor.module.exports.TextEditor.cursorMoved (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1686:27)
```

I'm using it with `nuclide`, and have disabled nearly all other plugins. This is on Atom 1.5.0.

**Comment by gandm** [comment]
Can you let me have an example of the JSX block where this occurs?

**Comment by girvo** [comment]
```
// @flow weak
'use strict';

import React, {
    View,
    StyleSheet,
    SegmentedControlIOS,
    Text,
    Navigator,
    Component,
    Image,
    TextInput,
    ScrollView,
    Dimensions,
} from 'react-native';

import SideMenu from 'react-native-side-menu';
import moment from 'moment';
import Menu from '../Menu';

// Base styles
import {
    core,
    colors,
    images,
    sizes,
    toolbar,
    cellList
} from '../../styles.ios.js';

// $FlowAsset
let addIcon = require('../../assets/icons/add@3x.png');
// $FlowAsset
let dotsIcon = require('../../assets/icons/dots@3x.png');
// $FlowAsset
let calendarIcon = require('../../assets/icons/calendar@3x.png');

type Booking = {
    child: string,
    date: moment,   // This is actually a `moment()` result
};

const fakeData: Array<Booking> = [
    {
        child: 'Jake',
        date: { test: 'lol' }
    },
    {
        child: 'Jake',
        date: moment().day('Tuesday')
    },
    {
        child: 'Jake',
        date: moment().day('Wednesday')
    },
    {
        child: 'Jake',
        date: moment().day('Friday')
    }
];

class BookingsList extends Component
{
    constructor(props) {
        super(props);

        this.state = {
            isOpen: false,
            selectedTab: 'notifications'
        };

        // Bind our methods to the 'this' context
        this.toggle = this.toggle.bind(this);
        this.updateMenuState = this.updateMenuState.bind(this);
    }

    toggle() {
        this.setState({
            isOpen: !this.state.isOpen
        })
    }

    updateMenuState(isOpen) {
        this.setState({isOpen});
    }

    render() {
        return (
            <SideMenu
                menu={<Menu {...this.props} />}
                isOpen={this.state.isOpen}
                onChange={(isOpen) => { this.updateMenuState(isOpen) }}>
                <View style={{
                    flex: 1,
                    flexDirection: 'column',
                    backgroundColor: colors.toolbar.background
                    }}
                      scrollEnabled={false}>

                    <View style={
                        Object.assign(
                            {},
                            toolbar.wrapper,
                            { borderColor: colors.toolbar.background }
                        )}>
                        <View style={toolbar.iconLeft}>
                            <Image onTouchEnd={this.toggle} source={images.menuBurger}/>
                        </View>
                        <Text style={toolbar.route}>
                            BOOKINGS
                        </Text>
                        <View style={{ alignItems: 'center' }}>
                            <Image source={addIcon} style={{ marginRight: 10 }}/>
                        </View>
                    </View>

                    <View style={toolbar.subWrapper}>
                        <View style={{ flex: 1 }}>{/* This is an offset */}</View>
                        <View style={{ flex: 1, paddingTop: 10 }}>
                            <Text>December</Text>
                        </View>
                        <View style={{ flex: 3, alignItems: 'flex-end', paddingRight: 20 }}>
                            <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                                <Image source={calendarIcon} style={{ marginRight: 30 }} />
                                <Image source={dotsIcon} />
                            </View>
                        </View>
                    </View>

                    <ScrollView style={listStyles.container}>
                        <View style={listStyles.dayRow}>
                            <View style={listStyles.internalRow}>
                                <View style={listStyles.dayCol}>
                                  <Text style={listStyles.dayText}>Mon</Text>
                                  <Text style={listStyles.dayText}>21</Text>
                                </View>
                                <View style={listStyles.detailCol}>
                                    <Text>Jake</Text>
                                    <Text>8am &mdash; 5.30pm</Text>
                                </View>
                            </View>
                        </View>
                    </ScrollView>
                </View>
            </SideMenu>
        );
    }
}

const listStyles = {
    container: {
        flexDirection: 'column',
        padding: 0,
        margin: 0,
    },

    dayRow: {
        borderBottomWidth: 2,
        borderBottomColor: '#4A4A4A',
        padding: 0,
    },

    internalRow: {
        borderBottomWidth: 1,
        borderBottomColor: '#ececed',
        flexDirection: 'row',
        padding: 0,
        margin: 0,
        alignItems: 'center',
    },

    dayCol: {
        paddingTop: 15,
        paddingBottom: 15,
        backgroundColor: '#4A4A4A',
        flex: 1,
    },

    dayText: {
        color: '#fff',
        textAlign: 'center',
        fontWeight: 'bold',
    },

    detailCol: {
        backgroundColor: 'transparent',
        flex: 5,
    }
};

export default BookingsList;
```

Latest version of `language-babel` 2.15.3

![](https://i.imgur.com/3519QNq.png)

**Comment by gandm** [comment]
@girvo OK thanks. I can see the issue and will try and fix asap. If it blocks you you can disable the autoIndentJSX by using the package global settings or via a language-babel command as mentioned in the readme.

**Comment by girvo** [comment]
@gandm Thank you! :) Hope this helped

**Comment by gandm** [comment]
@girvo Thanks for the source code above, it was very helpful. Should be fixed now.
