### ISSUE TITLE
Uncaught AssertionError: true === false with Atom 1.0.2 upgrade

### ISSUE THREAD

**Issue by gilbox** [gandm/language-babel#17]
Since upgrading atom today I'm getting this error all the time.
```
Uncaught AssertionError: true === false

/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:774
Hide Stack Trace
AssertionError: true === false
  at Def.Dp.bases (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/ast-types/lib/types.js:408:12)
  at Object.<anonymous> (/Users/gbirman/.atom/packages/language-babel/node_modules/babel-core/lib/babel/patch.js:45:26)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/gbirman/.atom/packages/language-babel/node_modules/babel-core/lib/babel/util.js:21:1)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/gbirman/.atom/packages/language-babel/node_modules/babel-core/lib/babel/transformation/file/options/parsers.js:16:13)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/gbirman/.atom/packages/language-babel/node_modules/babel-core/lib/babel/transformation/file/options/index.js:13:16)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/gbirman/.atom/packages/language-babel/node_modules/babel-core/lib/babel/transformation/file/index.js:15:16)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/gbirman/.atom/packages/language-babel/node_modules/babel-core/lib/babel/transformation/plugin.js:37:13)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/gbirman/.atom/packages/language-babel/node_modules/babel-core/lib/babel/transformation/transformer.js:11:15)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/gbirman/.atom/packages/language-babel/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:15:20)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/gbirman/.atom/packages/language-babel/node_modules/babel-core/lib/babel/transformation/pipeline.js:11:26)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/gbirman/.atom/packages/language-babel/node_modules/babel-core/lib/babel/transformation/index.js:11:17)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/gbirman/.atom/packages/language-babel/node_modules/babel-core/lib/babel/api/node.js:22:23)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/gbirman/.atom/packages/language-babel/node_modules/babel-core/index.js:1:80)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Transpiler.transpile (/Users/gbirman/.atom/packages/language-babel/lib/transpiler.coffee:37:15)
  at /Users/gbirman/.atom/packages/language-babel/lib/babel-transpiler.coffee:17:21
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:996:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:535:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:518:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:592:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:311:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

The error was thrown from the language-babel package. You can help by creating an issue. Please explain what actions triggered this error.
Create issue on the language-babel package
```

**Comment by gandm** [comment]
language-babel v0.10.0, babel 5.6.15 and  atom 1.0.2 work for me. spec tests are also working on WIndows and OSX.

What version of language-babel and babel-core do you have? babel-core version can be found  in package.json at /Users/gbirman/.atom/packages/language-babel/node_modules/babel-core, language-babel version is in settings. AI also need the config.cson for atom ( in particular the language-babel properties ) as it could be a combination of flags.

**Comment by gandm** [comment]
I also need any `.babelrc` files that may be in any source file path directories.

**Comment by stephanebachelier** [comment]
Same error for me:
```bash
$ apm -v
apm  1.0.1
npm  2.5.1
node 0.10.35
python 2.7.6
```

Also:
atom 1.0.2
language-babel@0.10.0
babel-core 5.6.15

In config.cson:
```cson
"language-babel": {}
```

FYI the error is thrown on every JS file even if it is es5.

For now I've disabled babel transpilation when no .babelrc file is present which works for me as I don't use es6 in my current project.

**Comment by gandm** [comment]
I can't recreate this. The stack trace indicates the issue is deep inside babel-core and not within atom or language-babel. But something very weird is happening. 

>AssertionError: true === false
  at Def.Dp.bases (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/ast-types/lib/types.js:408:12)
  at Object.<anonymous> (/Users/gbirman/.atom/packages/language-babel/node_modules/babel-core/lib/babel/patch.js:45:26)
  at Module._compile (module.js:452:26)

The above stack trace shows babel-core under language-babel/node_modules is requiring a module from atom's version of babel-core. The only reason I can think this is happening is if node has cached the ast-types module from a previous save of a file that contains a `"use babel"` statement. Atom also ships babel-core; but at version 5.1.11; this would be total incompatible with the version I ship!!!

**Comment by gandm** [comment]
Do any atom packages you use do a dynamic compile by using "use babel"?

**Comment by gilbox** [comment]
I'm not exactly sure what you mean by `use babel`. My project has a `gulpfile.js` that looks like this.

```
require("babel/register");
require('./gulpfile.es6');
```

However, I actually have not had any more errors after restarting atom a few times yesterday. Thanks so much for your comments. It will help me try to debug this. I'll let you know if it comes up again. You can close this issue if you would like.

**Comment by gandm** [comment]
@gilbox Thanks for that. I'm pretty sure it's because the package wasn't quite updated completely when you tried to save and we were using a version of ast-types provided by atom that was incompatible. Provided the package was completely updated a reload of Atom would fix the issue.

@stephanebachelier Do you still have an issue?

**Comment by ezsper** [comment]
I'm getting this issue too.

Node version v0.12.7
Atom 1.0.2
Only with Nuclide package installed

AssertionError: true === false
  at Def.Dp.bases (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\babel-core\node_modules\ast-types\lib\types.js:408:12)
  at Object.<anonymous> (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\babel-core\lib\babel\patch.js:45:26)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\babel-core\lib\babel\util.js:21:1)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\babel-core\lib\babel\transformation\file\options\parsers.js:16:13)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\babel-core\lib\babel\transformation\file\options\index.js:13:16)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\babel-core\lib\babel\transformation\file\index.js:15:16)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\babel-core\lib\babel\transformation\plugin.js:37:13)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\babel-core\lib\babel\transformation\transformer.js:11:15)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\babel-core\lib\babel\transformation\file\plugin-manager.js:15:20)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\babel-core\lib\babel\transformation\pipeline.js:11:26)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\babel-core\lib\babel\transformation\index.js:11:17)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\babel-core\lib\babel\api\node.js:22:23)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\babel-core\index.js:1:80)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at transpile (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:126:15)
  at Object.loadFile [as .js] (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:165:67)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Ezequiel\.atom\packages\nuclide-flow\node_modules\nuclide-client\node_modules\nuclide-service-transformer\lib\main.js:13:38)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:166:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at createRemoteService (C:\Users\Ezequiel\.atom\packages\nuclide-flow\node_modules\nuclide-client\lib\service-manager.js:127:19)
  at getService (C:\Users\Ezequiel\.atom\packages\nuclide-flow\node_modules\nuclide-client\lib\service-manager.js:117:27)
  at Object.getServiceByNuclideUri (C:\Users\Ezequiel\.atom\packages\nuclide-flow\node_modules\nuclide-client\lib\service-manager.js:86:10)
  at getServiceByNuclideUri (C:\Users\Ezequiel\.atom\packages\nuclide-flow\lib\main.js:13:36)
  at Object.getSuggestions (C:\Users\Ezequiel\.atom\packages\nuclide-flow\lib\main.js:48:14)
  at C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:255:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:234:17)
  at AutocompleteManager.getSuggestionsFromProviders (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:221:19)
  at C:\Users\Ezequiel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61

**Comment by ezsper** [comment]
The problem seams to occur with nuclide-flow with language-babel, so I disabled nuclide-flow, now I'm not getting the error anymore, but I'm getting the following error when I save a js file:

"Failed to save remote file: Maximum call stack size exceeded"

It only stop occurring when I disable the language-babel pack, I didn't test this on local file, this is happening with me when editing a remote file with nuclide-remote-projects.

**Comment by ezsper** [comment]
My remote project babelrc has the following:

    {
      "stage": 0,
      "loose": "all"
    }

**Comment by ezsper** [comment]
I could manage to stop the error: "Failed to save remote file: Maximum call stack size exceeded" by disabling the "Transpile On Save" option in the language-babel package settings.

**Comment by gandm** [comment]
On holiday at the moment but I'll investigate when I return. Are you using Nuclide's remote file option or some other system?

**Comment by ezsper** [comment]
Just nuclide remote
Em 22/07/2015 03:15, "Graham" <notifications@github.com> escreveu:

**Comment by gandm** [comment]
@exsper OK I can't test this as I don't use OSX for dev. Nuclide doesn't support Windows fully e.g. Nuclide remote requires Watchman which isn't available for Windows, nor is Flow supported on Windows. I notice from the stack trace that you use Windows so I don't know how you got it working.

**Comment by ezsper** [comment]
My remote server is Linux and I have the nuclide server, flow and watchman installed and running there. As far as I know, I don't need to install these in my local server as well. Nuclide remote project do a bridge between my local Atom running app on Windows to the Nuclide Server installed on my Linux dev server.

**Comment by gandm** [comment]
ok i'll config my Ubuntu server and try to test this.

**Comment by gandm** [comment]
@ezsper I can't seem to recreate the problem. Do you still have it or are you not using language-babel?

**Comment by ezsper** [comment]
Sorry, I really don't know anymore, I was having problems with a couple of other packages with Nuclide and right now, I'm just using es6-javascript package instead and it's working for me. I'm reactivating your package, I'll report if I got any problems with Nuclide.
