### ISSUE TITLE
On Ubuntu problems on load for 'Source preview'

### ISSUE THREAD

**Issue by morhook** [gandm/language-babel#189]
I'm having some issues to load this plugin along with `source-preview` and `source-preview-babel` and using the 'Source Preview: toggle' command. It is just showing the same source as the source file (no transpiling).

Steps to reproduce:
* When installing the 'source-preview' works fine. 
* After restart of Atom it doesn't work and shows same code as before transpiling.

Patch-way:
* After making a 'disable' -> 'enable' of this plugin (`language-babel`) fixes the issue until next restart of Atom

As a side note, I'm using Ubuntu in an ember project (maybe this is affecting the plugins?)

**Comment by gandm** [comment]
You shouldn't be using source-preview-babel in conjunction with language-babel it is only a Babel v5 system and not authored or used by me.

language-babel is a Babel transpiler server that uses source-preview to view output. If the preview still shows the same syntax then you no Babel transform plugins specified in your project's .babelrc or package.json file.

**Comment by morhook** [comment]
Ok!

I'll add this .babelrc

```json
{
    "presets": ["es2015"] 
}
```

And install the npm module:

```bash
npm i babel-preset-es2015 --save-dev
```

**Comment by morhook** [comment]
I think something of this is incompatible with ember build. I'm having an error when running ember commands (but this might be more related with ember-cli than this project though).

```
File: modules/adc-wizard/components/adc-wizard/component.js
The Broccoli Plugin: [Babel] failed with:
ReferenceError: [BABEL] modules/adc-wizard/components/adc-wizard/component.js: Unknown option: /home/cruz/workspace/adc-wizard/.babelrc.presets
    at Logger.error (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:127:29)
    at OptionManager.addConfig (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:169:35)
    at OptionManager.init (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:230:12)
    at File.initOptions (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Babel.transform (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:94:21)
    at Babel.processString (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:123:25)
    at Promise.then.result.output (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:41:23)
    at lib$rsvp$$internal$$initializePromise (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1084:9)
    at new lib$rsvp$promise$$Promise (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:546:53)
    at /home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:40:18
    at lib$rsvp$$internal$$tryCatch (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1048:17)

The broccoli plugin was instantiated at: 
    at Babel.Plugin (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/index.js:38:10)
    at new Babel (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:34:10)
    at Babel (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:29:12)
    at Object.registry.add.toTree (/home/cruz/workspace/adc-wizard/node_modules/ember-cli-babel/index.js:21:52)
    at /home/cruz/workspace/adc-wizard/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/home/cruz/workspace/adc-wizard/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at Function.module.exports.preprocessJs (/home/cruz/workspace/adc-wizard/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:175:10)
    at Class.Addon.preprocessJs (/home/cruz/workspace/adc-wizard/node_modules/ember-cli/lib/models/addon.js:730:23)
    at Class.Addon.processedAddonJsFiles (/home/cruz/workspace/adc-wizard/node_modules/ember-cli/lib/models/addon.js:742:15)
    at Class.Addon.compileAddon (/home/cruz/workspace/adc-wizard/node_modules/ember-cli/lib/models/addon.js:652:22)
    at Class.Addon.treeForAddon (/home/cruz/workspace/adc-wizard/node_modules/ember-cli/lib/models/addon.js:403:24)
    at Class._treeFor (/home/cruz/workspace/adc-wizard/node_modules/ember-cli/lib/models/addon.js:322:31)
    at Class.treeFor (/home/cruz/workspace/adc-wizard/node_modules/ember-cli/lib/models/addon.js:290:19)
    at /home/cruz/workspace/adc-wizard/node_modules/ember-cli/lib/broccoli/ember-app.js:463:20
```

**Comment by gandm** [comment]
No I don't think it's the package but something to do with Broccoli. You would likely get the error using babel-cli. Looking at the brocolli plugin [here](https://github.com/babel/broccoli-babel-transpiler) it looks like they only support Babel v5 as per this [issue](https://github.com/babel/broccoli-babel-transpiler/issues/62) indicating no Babel v6 support yet.

If that is the case you need to remove any presets and install Babel-core version 5 in the project. I will then pick up v5 of Babel for this project.

**Comment by gandm** [comment]
Just to be clear. If you create a new [ember-cli-babel](https://github.com/babel/ember-cli-babel) project it will install the brocolli transpiler and the Babel core v5. You need to then add the brocolli plugin to the .babelrc file. As this is v5 no presents will be required as it was less flexible but simpler and just took es6 and output es5. When the project is opened in Atom, language-babel will find the Babel v5 image in node-modules and use that to compile you code.

**Comment by morhook** [comment]
Thanks!! I've tested both solutions:
* adding babel-core 5.8.38 to package.json (this is same version as broccoli-babel-transpiler) 
* adding an empty JSON .babelrc also fixes the problem

Just by adding this to `.babelrc`:

```json
{
}
```

**Comment by morhook** [comment]
Sorry for the re-open. Wrong click

**Comment by gandm** [comment]
@morhook No problems. I hope you get some luck with ember and language-babel.

**Comment by morhook** [comment]
Thanks @gandm ! So far so good! Added `"babel-core":"^5.0.0"` to my package.json internal project
