### ISSUE TITLE
error closing tab with atom beta

### ISSUE THREAD

**Issue by aeosynth** [gandm/language-babel#202]
with atom 1.9 beta0, i have this error when closing tabs:

```
/home/james/.atom/packages/language-babel/lib/auto-indent.coffee:62

TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.
    at TypeError (native)
    at AutoIndent.module.exports.AutoIndent.destroy (/home/james/.atom/packages/language-babel/lib/auto-indent.coffee:62:14)
    at /home/james/.atom/packages/language-babel/lib/main.coffee:41:50
    at Function.module.exports.Emitter.simpleDispatch (/usr/local/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/local/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditor.module.exports.TextEditor.destroyed (/usr/local/share/atom-beta/resources/app.asar/src/text-editor.js:389:27)
    at TextEditor.module.exports.Model.destroy (/usr/local/share/atom-beta/resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroyItem (/usr/local/share/atom-beta/resources/app.asar/src/pane.js:641:18)
    at atom-tabs.TabBarView.onMouseDown (/usr/local/share/atom-beta/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:669:19)
```

**Comment by gandm** [comment]
Try 2.26.3

**Comment by aeosynth** [comment]
works after restart, thanks
