### ISSUE TITLE
Failed to load a language-babel package grammar

### ISSUE THREAD

**Issue by rtfpessoa** [gandm/language-babel#244]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package, v2.36.3

### Stack Trace

Failed to load a language-babel package grammar

```
At Grammar missing required scopeName property: /Users/rtfpessoa/.atom/packages/language-babel/grammars/Babel Language.json in /Users/rtfpessoa/.atom/packages/language-babel/grammars/Babel Language.json

Error: Grammar missing required scopeName property: /Users/rtfpessoa/.atom/packages/language-babel/grammars/Babel Language.json
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar-registry.js:122:64
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:180:53
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
  at /Users/rtfpessoa/.atom/packages/language-babel/grammars/Babel Language.json:1:1
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "react"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.11 (inactive)
atom-terminal, v0.8.0 (inactive)
atomatigit, v1.5.5 (active)
auto-update-packages, v1.0.1 (active)
clang-format, v1.25.0 (active)
color-picker, v2.2.2 (active)
format-sql, v0.3.0 (inactive)
gist-it, v0.9.1 (inactive)
git-diff-popup, v0.1.8 (inactive)
git-plus, v5.16.2 (inactive)
haskell-grammar, v0.4.0 (inactive)
highlight-selected, v0.11.2 (active)
hyperclick, v0.0.37 (active)
javascript-snippets, v1.2.1 (active)
language-babel, v2.36.3 (inactive)
language-csharp, v0.12.1 (inactive)
language-diff, v0.4.0 (inactive)
language-ini, v1.16.0 (inactive)
language-latex, v0.6.1 (inactive)
language-lisp, v0.2.0 (inactive)
language-nginx, v0.6.1 (inactive)
language-ocaml, v1.1.2 (inactive)
language-scala, v1.1.6 (inactive)
language-scala-plus, v1.2.2 (inactive)
language-thrift, v1.0.2 (inactive)
markdown-pdf, v1.5.0 (inactive)
minimap, v4.25.0 (active)
monokai, v0.18.0 (inactive)
pdf-view, v0.50.0 (active)
pretty-json, v1.6.0 (active)
show-in-system, v0.4.0 (inactive)
sort-lines, v0.14.0 (inactive)
status-bar, v1.4.1 (active)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by rtfpessoa** [comment]
I uninstalled and installed again and restarted and finally it worked. Weird. Sorry for the report.

**Comment by MaxBittker** [comment]
thanks for the report, helped me fix my state @rtfpessoa
