### ISSUE TITLE
Cannot find module './scorer'

### ISSUE THREAD

**Issue by MateuszFlisikowski** [gandm/language-babel#247]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.1
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Home
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package, v2.37.0

### Stack Trace

Failed to load the language-babel package

```
At Cannot find module './scorer'

Error: Cannot find module './scorer'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\mateusz\AppData\Local\atom\app-1.10.1\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\mateusz\AppData\Local\atom\app-1.10.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\mateusz\.atom\packages\language-babel\node_modules\fuzzaldrin\lib\fuzzaldrin.js:4:12)
    at Object.<anonymous> (C:\Users\mateusz\.atom\packages\language-babel\node_modules\fuzzaldrin\lib\fuzzaldrin.js:80:4)
    at Module._compile (C:\Users\mateusz\AppData\Local\atom\app-1.10.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\mateusz\AppData\Local\atom\app-1.10.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\mateusz\AppData\Local\atom\app-1.10.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/mateusz/.atom/packages/language-babel/lib/auto-complete-jsx.coffee:2:19)
    at Object.<anonymous> (file:///C:/Users/mateusz/.atom/packages/language-babel/lib/auto-complete-jsx.coffee:1:1)
    at Module._compile (C:\Users\mateusz\AppData\Local\atom\app-1.10.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\mateusz\AppData\Local\atom\app-1.10.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\mateusz\AppData\Local\atom\app-1.10.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/mateusz/.atom/packages/language-babel/lib/main.coffee:2:19)
    at Object.<anonymous> (file:///C:/Users/mateusz/.atom/packages/language-babel/lib/main.coffee:1:1)
    at Module._compile (C:\Users\mateusz\AppData\Local\atom\app-1.10.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\mateusz\AppData\Local\atom\app-1.10.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\mateusz\AppData\Local\atom\app-1.10.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\mateusz\AppData\Local\atom\app-1.10.1\resources\app.asar\src\package.js:718:27)
```

### Commands

```
     -0:01.4.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.compact-tab-bar.panel-contrast.use-animations.compact-tree-view.theme-one-dark-syntax.theme-atom-material-ui.has-custom-icons)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "auto-detect-indentation",
      "jslint",
      "lint"
    ],
    "ignoredNames": [
      "node_modules"
    ],
    "packagesWithKeymapsDisabled": [
      "css-comb",
      "atom-sync",
      "gulp-control",
      "atom-csscomb",
      "merge-conflicts",
      "grunt-runner",
      "bottom-dock",
      "gulp-manager",
      "jslint",
      "atom-beautify"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.11 (inactive)
atom-lorempixel, v0.1.0 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-notifier, v0.5.1 (inactive)
atom-sync, v0.7.3 (inactive)
auto-reveal-in-sidebar, v0.8.0 (inactive)
autocomplete-modules, v1.6.1 (inactive)
color-picker, v2.2.2 (inactive)
css-comb, v2.5.0 (inactive)
csscomb, v0.3.1 (inactive)
docblockr, v0.8.5 (inactive)
editorconfig, v1.4.1 (inactive)
emmet, v2.4.3 (inactive)
file-icons, v1.7.19 (inactive)
file-type-icons, v1.3.2 (inactive)
git-checkout, v0.3.2 (inactive)
git-hide, v0.1.2 (inactive)
haskell-grammar, v0.4.0 (inactive)
highlight-line, v0.11.1 (inactive)
highlight-selected, v0.11.2 (inactive)
indent-guide-improved, v1.4.10 (inactive)
javascript-snippets, v1.2.1 (inactive)
jshint, v1.8.6 (inactive)
jslint, v1.5.1 (inactive)
keyboard-localization, v1.4.18 (inactive)
language-babel, v2.37.0 (inactive)
language-ini, v1.16.0 (inactive)
language-log, v1.5.0 (inactive)
language-thrift, v1.0.2 (inactive)
lint, v0.0.1 (inactive)
linter, v1.11.16 (inactive)
linter-csslint, v1.3.2 (inactive)
linter-eslint, v7.2.4 (inactive)
linter-flow, v5.5.0 (inactive)
linter-htmlhint, v1.3.0 (inactive)
linter-jshint, v2.1.0 (inactive)
merge-conflicts, v1.4.4 (inactive)
minimap, v4.25.0 (inactive)
minimap-highlight-selected, v4.4.0 (inactive)
minimap-pigments, v0.2.1 (inactive)
open-recent, v5.0.0 (inactive)
pigments, v0.34.0 (inactive)
react-es6-snippets, v0.3.0 (inactive)
save-session, v0.15.7 (inactive)
sort-lines, v0.14.0 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (inactive)
sync-settings, v0.7.2 (inactive)
todo-show, v1.7.0 (inactive)
tool-bar, v1.0.1 (inactive)
uglify, v1.2.6 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.39.0 (inactive)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.2 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.65.0 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.208.2 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by MateuszFlisikowski** [comment]
Hi, after reinstalling the problem disappeared

**Comment by gandm** [comment]
Yeah! the Atom installer seems to give issues like this. Seems like the cache often gets out of step or incomplete on updates.
