### ISSUE TITLE
Failed to activate the language-babel package

### ISSUE THREAD

**Issue by pingshunhuangalex** [gandm/language-babel#331]
[Enter steps to reproduce:]

0. Issue once happened in [here](https://github.com/gandm/language-babel/issues/87), but I'm using the latest version of Atom...
1. Fire up Atom
2. Check the notification area

**Atom**: 1.15.0-beta3 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package 2.55.3

### Stack Trace

Failed to activate the language-babel package

```
At unexpected indentation in file:///C:/Users/Pingshun Huang/.atom/packages/language-babel/lib/did-insert-text.coffee:20:1

SyntaxError: unexpected indentation
  at /packages/language-babel/lib/did-insert-text.coffee:20:1
```

### Commands

```
     -2:34.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.tinted-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.blend-tree-view.paint-cursor.theme-atom-material-syntax-dark.theme-atom-material-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
aligner 0.22.3 
atom-beautify 0.29.17 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.9 
atom-terminal 0.8.0 
atom-ternjs 0.17.2 
autocomplete-modules 1.6.7 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.55 
autoprefixer 3.6.1 
color-picker 2.2.5 
d3-snippets 0.2.0 
django-atom 0.2.4 
emmet 2.4.3 
file-icons 2.0.15 
git-log 0.4.1 
git-plus 7.3.2 
git-time-machine 1.5.6 
highlight-selected 0.12.0 
Hydrogen 1.5.5 
hyperclick 0.0.40 
js-hyperclick 1.10.1 
language-babel 2.55.3 
linter 1.11.23 
linter-coffeelint 1.2.1 
linter-csslint 1.3.4 
linter-eslint 8.1.2 
linter-flake8 2.1.4 
linter-jsonlint 1.3.0 
linter-markdown 3.1.0 
linter-xmllint 1.4.0 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-pigments 0.2.2 
pigments 0.39.0 
project-manager 3.3.3 
qolor 0.4.1 
regex-railroad-diagram 0.16.0 
split-diff 1.2.0 
sync-settings 0.8.1 
tree-view-git-status 1.3.1 
```

**Comment by gandm** [comment]
Yeah, sorry about that-  bit rushed. Try 2.55.4

**Comment by dodekeract** [comment]
Funny how fast people upgrade. 🙂

**Comment by pingshunhuangalex** [comment]
All good now. :)

**Comment by Jones-S** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package 2.65.1


### Stack Trace

Failed to activate the language-babel package

```
At Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at Array.indexOf (native)
    at Object._.contains._.include (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore/underscore.js:219:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:294:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
    at Grammar.module.exports.Grammar.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:298:1)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:181:1)
  

... a lot more like this


(/Applications/Atom.app/Contents/Resources/app/src/config.js:236:1)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:386:1)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:84:1)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:185:1)
    at HTMLButtonElement.enablementButtonClickHandler (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:361:1)
```

### Commands

```
     -0:51.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:34.5.0 core:paste (input.hidden-input)
     -0:23 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
auto-reveal-in-sidebar 0.8.0 
busy-signal 1.4.1 
color-picker 2.2.5 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.7 
intentions 1.1.2 
language-babel 2.65.1 
language-javascript-jsx 0.3.7 
language-vue 0.22.1 
linter 2.0.0 
linter-eslint 8.2.1 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.0 
```
