### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of null

### ISSUE THREAD

**Issue by JacopKane** [gandm/language-babel#34]
This error pops up whenever babel will starting to transpile a file on save.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package, v0.10.3

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of null

```
At /Users/furkantunali/.atom/packages/language-babel/lib/transpiler.coffee:79

TypeError: Cannot read property 'version' of null
  at /Users/furkantunali/.atom/packages/language-babel/lib/transpiler.coffee:79:32
  at /Users/furkantunali/.atom/packages/language-babel/node_modules/babel-core/lib/api/node.js:121:5
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)

```

### Commands

```
     -1:31.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:31.6.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:31.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:31.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:31.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:31.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:29.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:29.5.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:28.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:28.2.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -1:26.5.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:25.2.0 script:run (atom-text-editor.editor.is-focused)
     -0:10.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:10.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:07.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/furkantunali/Sites",
    "disabledPackages": [
      "deprecation-cop",
      "recent-files",
      "browser-refresh"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "language-babel": {
    "createTranspiledCode": true,
    "disableWhenNoBabelrcFileInPath": true,
    "babelSourcePath": "src",
    "babelTranspilePath": "dist",
    "externalHelpers": true,
    "suppressSourcePathMessages": true,
    "babelMapsAddUrl": false,
    "createMap": true
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-beautify, v0.28.8
atom-color-highlight, v3.0.9
autocomplete-paths, v1.0.2
autocomplete-phpunit, v1.0.2
browser-plus, v0.0.30
build, v0.42.0
docblockr, v0.7.3
editorconfig, v1.0.1
emmet, v2.3.12
file-icons, v1.5.8
file-types, v0.5.1
highlight-selected, v0.10.1
indentation-indicator, v0.6.0
language-SCSS, v0.4.0
language-apache, v1.3.0
language-babel, v0.10.3
language-css, v0.32.1
language-dotenv, v1.0.0
language-fish-shell, v1.0.2
language-generic-config, v0.2.0
language-gettext, v0.6.1
language-gitignore, v0.2.0
language-hosts, v0.1.2
language-ini, v1.11.0
language-javascript, v0.85.0
language-liquid, v0.4.0
language-mustache, v0.12.0
less-autocompile, v1.0.0
linter, v1.2.4
linter-bootlint, v0.0.6
linter-coffeelint, v1.0.0
linter-csslint, v0.0.14
linter-eslint, v3.0.1
linter-handlebars, v2.0.0
linter-htmlhint, v0.0.17
linter-jscs, v1.13.0
linter-jshint, vundefined
linter-jsonlint, v0.1.4
linter-less, v2.0.3
linter-php, v1.0.2
linter-phpcs, v1.0.6
linter-phpmd, v1.0.0
linter-pylint, v0.2.2
linter-recess, v0.0.1
linter-ruby, v0.1.6
linter-scss-lint, v2.0.0
linter-shellcheck, v0.0.8
local-history, v3.2.3
minimap, v4.12.1
minimap-color-highlight, v4.1.4
minimap-selection, v4.3.0
node-debugger, v1.1.6
pigments, v0.9.2
remote-atom, v1.2.6
sass-autocompile, v0.7.3
sass-compiler, v0.4.0
sass-watch, v0.3.1
script, v2.26.3
soft-wrap-indicator, v0.7.0
ssh-config, v0.10.1
tab-control, vundefined
tabs-to-spaces, v0.11.0
theme-switcher, v1.1.0

# Dev
No dev packages
```

**Comment by JacopKane** [comment]
Apparently it's not happening when 'Create map' option is disabled.

**Comment by gandm** [comment]
I'm guessing you have a `.babelrc` file in the path that has a `sourceMaps` option set to `inline`? If so you must disable the mapping option as the source file itself has the mapping info appended to it. This is mentioned in the README. Having said that I shouldn't gen this error so I will put in a check to stop it.

**Comment by JacopKane** [comment]
@gandm I see... Yeah that's correct. Sorry that I missed that info. Thanks !
