### ISSUE TITLE
...

### ISSUE THREAD

**Issue by Karmaliu** [gandm/language-babel#344]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package, v2.57.0

### Stack Trace

Failed to load the language-babel package

```
At Proxy is not defined

ReferenceError: Proxy is not defined
    at Object.<anonymous> (C:\Users\yuan\node_modules\fs-plus\lib\fs-plus.js:708:24)
    at Object.<anonymous> (C:\Users\yuan\node_modules\fs-plus\lib\fs-plus.js:718:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (C:\Users\yuan\AppData\Local\atom\app-1.2.4\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (file:///C:/Users/yuan/.atom/packages/language-babel/lib/auto-indent.coffee:2:6)
    at Object.<anonymous> (file:///C:/Users/yuan/.atom/packages/language-babel/lib/auto-indent.coffee:1:1)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "react-es6-snippets",
      "react-es6-snippets",
      "react-es6-snippets"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.4
atom-react-native-autocomplete, v0.0.27
language-babel, v2.57.0

# Dev
No dev packages
```

**Comment by gandm** [comment]
This is a problem with Atom, in particular the fs-plus module has an issue with Node 4. See https://github.com/atom/fs-plus/issues/38

I would strongly suggest you update Atom as you are running a very old version. If you can't do that then
I would suggest you go to ~/.atom/.apm/fs-plus and do an npm update to get the latest version that supports Node 4.
