### ISSUE TITLE
Failed to activate the language-babel package

### ISSUE THREAD

**Issue by Aleon-Sully** [gandm/language-babel#383]
I just downloaded the language-babel cos I wanted to start react native but it right after installing it threw ;

Cannot find module 'fuzzaldrin'. here is the stack trace.

Error: Cannot find module 'fuzzaldrin'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/aleon/.atom/packages/language-babel/lib/auto-complete-jsx.coffee:2:19)
    at Object.<anonymous> (file:///C:/Users/aleon/.atom/packages/language-babel/lib/auto-complete-jsx.coffee:1:1)
    at Module._compile (C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .coffee] (C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/aleon/.atom/packages/language-babel/lib/main.coffee:2:19)
    at Object.<anonymous> (file:///C:/Users/aleon/.atom/packages/language-babel/lib/main.coffee:1:1)
    at Module._compile (C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .coffee] (C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:796:27)
    at Package.module.exports.Package.activateNow (C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:207:16)
    at C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:190:32
    at Package.module.exports.Package.measure (C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:96:15)
    at C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:183:26
    at Package.module.exports.Package.activate (C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:484:29
    at exit (C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:99:16)
    at triggerExitCallback (C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\aleon\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)

**Comment by gandm** [comment]
Probably an Atom installer issue. See https://github.com/gandm/language-babel/issues/142 
Uninstall. Stop Atom. Use `apm install language-babel` and then restart Atom.

**Comment by fuXiangRong** [comment]
找不到'fuzzaldrin' 模块

**Comment by caseywebdev** [comment]
I've having this problem now and reinstalling `language-babel` via `apm` didn't fix it. Tried a few times. Started happening in Atom `1.23.0` and is still happening in `1.23.1`. Any ideas?

**Comment by gandm** [comment]
@caseywebdev you could try uninstalling language-babel, stop atom, remove ~.atom/compile-cache, apm install language-babel and then restart atom.

**Comment by caseywebdev** [comment]
Thanks @gandm that fixed it!
