### ISSUE TITLE
Uncaught TypeError: Cannot read property 'blockHeight' of undefined

### ISSUE THREAD

**Issue by rainjm** [gandm/language-babel#415]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.6
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package 2.74.2

### Stack Trace

Uncaught TypeError: Cannot read property 'blockHeight' of undefined

```
At /Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:899

TypeError: Cannot read property 'blockHeight' of undefined
    at LineTopIndex.adjustNodeBlockHeight (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/node_modules/line-top-index/dist/line-top-index.js:313:17)
    at LineTopIndex.removeBlock (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/node_modules/line-top-index/dist/line-top-index.js:78:18)
    at marker.bufferMarker.onDidChange (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/src/text-editor-component.js:2524:35)
    at Function.module.exports.Emitter.simpleDispatch (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Marker.module.exports.Marker.emitChangeEvent (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:424:26)
    at /Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-layer.js:324:31
    at Set.forEach (native)
    at MarkerLayer.module.exports.MarkerLayer.emitChangeEvents (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-layer.js:321:52)
    at TextBuffer.module.exports.TextBuffer.emitMarkerChangeEvents (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1561:40)
    at TextBuffer.module.exports.TextBuffer.transact (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:924:18)
    at TextEditor.module.exports.TextEditor.transact (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at /Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:1234:30
    at TextEditor.module.exports.TextEditor.mergeSelections (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:2621:24)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:2583:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:1232:25)
    at TextEditor.module.exports.TextEditor.insertText (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:1198:25)
    at TextEditor.object.(anonymous function) (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at /packages/language-babel/lib/did-insert-text.coffee:80:18)
    at TextEditor.module.exports.TextEditor.insertNewline (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:1213:25)
    at TextEditor.object.(anonymous function) [as insertNewline] (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditor.editor:newline (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/src/register-default-commands.js:617:27)
    at /Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/src/register-default-commands.js:677:40
    at TextBuffer.module.exports.TextBuffer.transact (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:894:24)
    at TextEditor.module.exports.TextEditor.transact (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at HTMLElement.newCommandListeners.(anonymous function) (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/src/register-default-commands.js:676:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Users/Jimmy/Downloads/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:22.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:09.5.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:09.5.0 docblockr:parse-enter (input.hidden-input)
     -0:09.5.0 editor:newline (input.hidden-input)
     -0:06.2.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:06.2.0 docblockr:parse-enter (input.hidden-input)
     -0:06.2.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
api-docs 0.0.6 
atom-beautify 0.30.5 
atom-clock 0.1.15 
atom-include-path 0.1.0 
atom-terminal-panel 4.4.4 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-js-import 1.4.0 
autocomplete-json 5.5.0 
autocomplete-modules 1.7.0 
autocomplete-paths 2.11.0 
busy-signal 1.4.3 
color-picker 2.2.5 
css-snippets 1.1.0 
dash 1.7.1 
docblockr 0.11.0 
drag-relative-path 1.1.3 
editorconfig 2.2.2 
elastic-tabstops 1.2.0 
emmet 2.4.3 
file-icons 2.1.12 
google-translate-modal 1.2.2 
highlight-selected 0.13.1 
html-head-snippets 0.2.0 
html-nested-comments 3.3.1 
hyperclick 0.1.5 
import-cost-atom 1.0.4 
intentions 1.1.5 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
js-hyperclick 1.11.1 
language-aspx 0.5.0 
language-babel 2.74.2 
language-vue 0.23.1 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-eslint 8.3.2 
linter-htmlhint 1.3.3 
linter-ui-default 1.6.10 
local-history 4.3.0 
markdown-preview-plus 2.4.10 
markdown-writer 2.7.2 
minimap 4.29.7 
nice-index 1.0.5 
open-terminal-here 2.3.1 
pigments 0.40.2 
prettier-atom 0.40.0 
project-viewer 1.2.0 
px2rem-plus 0.3.1 
regex-railroad-diagram 0.19.3 
relative-require 1.6.12 
simplified-chinese-menu 5.3.4 
split-diff 1.5.1 
structure-view 0.1.4 
sync-settings 0.8.3 
tag 0.5.0 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
tree-view-copy-relative-path 1.2.0 
tree-view-git-status 1.4.0 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by gandm** [comment]
I don't think the problem is with `language-babel` but some issue with Atom. Is this repeatable? How many times have you experienced it?

**Comment by rainjm** [comment]
![image](https://user-images.githubusercontent.com/9592236/30673510-3628746c-9e39-11e7-988a-2657e25b6990.png)
I tried to upgrade.

![mqptou0ql0](https://user-images.githubusercontent.com/9592236/30673711-a2a42518-9e3a-11e7-9f45-11e05e7848c8.gif)
But it did not work.

**Comment by gandm** [comment]
Still pretty sure it's an atom issue. I can't recreate it so it maybe another package has added singing to the DOM that atom is trying to measure. Maybe a decorator or something. 

The bit of code that is in the stack trace just checks if a new line has been entered between backticks or JSX tags and is fairly passive.

**Comment by gandm** [comment]
As this looks to be an issue with another package I'll close. If you feel that this is not the case then please post back here.
