### ISSUE TITLE
Uncaught TypeError: Cannot set property 'autoIndent' of undefined

### ISSUE THREAD

**Issue by smoliver** [gandm/language-babel#468]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package 2.81.1

### Stack Trace

Uncaught TypeError: Cannot set property 'autoIndent' of undefined

```
At /Users/SamO/.atom/packages/language-babel/lib/main.coffee:36

TypeError: Cannot set property 'autoIndent' of undefined
    at /packages/language-babel/lib/main.coffee:36:11
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.handleGrammarChange (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:4120:31)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TokenizedBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:242:24)
    at TextEditor.setGrammar (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3560:39)
    at TextEditorRegistry.setGrammarOverride (/Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:274:20)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/grammar-selector/lib/grammar-list-view.js:26:34)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/grammar-selector/node_modules/atom-select-list/src/select-list-view.js:327:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/grammar-selector/node_modules/atom-select-list/src/select-list-view.js:84:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:27.1.0 docblockr:parse-tab (input.hidden-input)
     -0:27.1.0 snippets:next-tab-stop (input.hidden-input)
     -0:27.1.0 snippets:expand (input.hidden-input)
     -0:27.1.0 editor:indent (input.hidden-input)
  3x -0:26.6.0 core:backspace (input.hidden-input)
     -0:25.3.0 docblockr:parse-tab (input.hidden-input)
     -0:25.3.0 snippets:next-tab-stop (input.hidden-input)
     -0:25.3.0 snippets:expand (input.hidden-input)
     -0:25.3.0 editor:indent (input.hidden-input)
  4x -0:24.9.0 core:backspace (input.hidden-input)
     -0:19.5.0 intentions:highlight (input.hidden-input)
  3x -0:19.4.0 editor:move-to-beginning-of-word (input.hidden-input)
     -0:18.1.0 core:move-right (input.hidden-input)
     -0:16.3.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:13.3.0 core:confirm (input.hidden-input)
     -0:04.9.0 grammar-selector:show (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-transpose 0.3.5 
atom-wrap-in-tag 0.6.0 
autocomplete-modules 1.8.0 
busy-signal 1.4.3 
case-keep-replace 0.6.1 
change-case 0.6.5 
color-picker 2.2.5 
copy-path 0.4.2 
docblockr 0.13.5 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
es6-javascript 1.0.0 
file-icons 2.1.15 
git-plus 7.10.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.12.2 
language-babel 2.81.1 
linter 2.2.0 
linter-ui-default 1.6.10 
local-history 4.3.1 
minimap-highlight-selected 4.6.1 
prettier-atom 0.46.0 
react-snippets 1.0.1 
related 0.3.5 
tab-foldername-index 3.2.2 
tree-view-copy-relative-path 1.2.0 
```

**Comment by gandm** [comment]
Curious. I can't see why this should be. Is it reproducible/frequent?
