### ISSUE TITLE
Failed to activate language-babel

### ISSUE THREAD

**Issue by RavikumarSelva** [gandm/language-babel#477]
Stack-Trace:
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package 2.83.1

### Stack Trace

Failed to activate the language-babel package

```
At Cannot find module 'fuzzaldrin'

Error: Cannot find module 'fuzzaldrin'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.14.3/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/language-babel/lib/auto-complete-jsx.coffee:2:19)
    at /packages/language-babel/lib/auto-complete-jsx.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/language-babel/lib/main.coffee:2:19)
    at /packages/language-babel/lib/main.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
```

### Commands

```
```

### Non-Core Packages

```
open_in_cmd 0.6.1 
aligner-javascript 1.2.0 
alignment 1.1.5 
es6-javascript 1.0.0 
atom-file-icons 0.6.0 
atom-nodejs-snippets 1.5.0 
plain-simple 1.1.0 
atom-react-mf-snippets 0.11.1 
html-shorcuts-react 1.1.1 
auto-close-html2 0.3.6 
autocomplete-javascript 0.0.2 
browser-plus 0.0.87 
formatter-jsbeautify 1.0.2 
fz-atom-react-snippet 0.0.2 
highlight-selected 0.13.1 
language-babel 2.83.1 
language-javascript-jsx 0.3.7 
monokai 0.24.0 
pure-syntax 0.2.1 
railscast 2.0.2 
react-es6-snippets 0.3.0 
redux-snippets 0.2.2 
```

**Comment by gandm** [comment]
Not installed correctly. See https://github.com/gandm/language-babel/issues/383
