### ISSUE TITLE
Failed to activate the language-babel package

### ISSUE THREAD

**Issue by WendyMin** [gandm/language-babel#518]
Can't auto Completion of JSX tags, elements and attributes.

Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisp

```
osable.add must have a .dispose() method
    at assertDisposable (C:\Users\mcw\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:1190530)
    at CompositeDisposable.add (C:\Users\mcw\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:1191498)
    at Object.consumeProvider (C:\Users\mcw\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:161432)
    at Object.consumeProvider_2 (C:\Users\mcw\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:161130)
    at Provider.t.exports.Provider.provide (C:\Users\mcw\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:14:1034525)
    at ServiceHub.t.exports.ServiceHub.provide (C:\Users\mcw\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:3027895)
    at Package.activateServices (C:\Users\mcw\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:3036081)
    at Package.activateNow (C:\Users\mcw\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:3033136)
    at measure (C:\Users\mcw\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:3032460)
    at Package.measure (C:\Users\mcw\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:3030091)
    at activationPromise.activationPromise.Promise (C:\Users\mcw\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:3032320)
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\mcw\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:3032263)
    at PackageManager.activatePackage (C:\Users\mcw\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:379950)
    at C:\Users\mcw\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:913945
    at r (C:\Users\mcw\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:908551)
    at o (C:\Users\mcw\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:14:1037432)
    at ChildProcess.n.process.on.e (C:\Users\mcw\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:14:1037638)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

**Comment by WendyMin** [comment]
Is anybody here to help me or have the same issue? :(

**Comment by billyjacoby** [comment]
Im having this same issue too...

**Comment by saulable** [comment]
Yep, my syntax highlighting is gone too.

**Comment by robin-macpherson** [comment]
Same here, I've been having this issue for the past few weeks :(

**Comment by 0xtelmo** [comment]
Same here. Have anyone figured out what's wrong?

**Comment by 0xtelmo** [comment]
Alright, this is pretty stupid, but I've found out that it keeps working just by changing the grammar to Babel.

Hope it helps.

**Comment by SamSteele01** [comment]
@telmogoncalves Can you elaborate on what you did?

**Comment by 0xtelmo** [comment]
@SamSteele01 on Atom, what I did is changing the grammar to Babel. On the bottom bar, you should see displaying what grammar the file you've opened is using.

**Comment by 0xtelmo** [comment]
If you're on Mac you can try this:

1. ⌘ + ⇧ + P
2. Type "grammar"
3. Type "babel"
4. Enter

**Comment by SamSteele01** [comment]
@telmogoncalves Thanks for the reply. I figured that out after posting here. I didn't like having to do it every time I opened a file. Did some digging... References this[ issue](https://github.com/gandm/language-babel/issues/510). The tl;dr is to uncheck tree-sitter parsing in core settings. For me I also had to move the 'themes' array into the 'core' object in config.cson. Like so:
```
// .atom/config.cson

core:
   ...
   themes: [
     "one-dark-ui"
     "babel-react-syntax"
   ]
```
