### ISSUE TITLE
`Callback must be a function` when using a custom tagged template grammar

### ISSUE THREAD

**Issue by pfgithub** [gandm/language-babel#525]
Setting a custom tagged template grammar like `csscustom:source.css` and using it on a file

```javascript
let csscustom = () => {};
csscustom`
a{
  color:#fff;
}
`;
```

produces a warning `Callback must be a function` and does not highlight the text differently

![settings page with template literal grammar set](https://i.imgur.com/ZAhNMkb.png)
![image of code above](https://i.imgur.com/CWF9J8f.png)
![callback must be a function](https://i.imgur.com/fNhaYtW.png)

**Comment by lasbian** [comment]
Same issue...

**Comment by tujoworker** [comment]
By installing Node v10 (LTS) instead of using v12, I got rid of the warning message `Callback must be a function`. But my custom tagged template grammar extensions are currently not working on my new mac/atom setup.

**Comment by lasbian** [comment]
Was already running the v10 (LTS) :/

**Comment by pyrou** [comment]
Same issue here. 
Possible related issue: are gql code highlighted on your setup with following example ?

```javascript
const typeDefs = gql`
  type Query {
    test: String
  }
`;
```

This highlight should be working without custom tagged template grammar, because shipped by default with the plugin, but is also not working anymore on my setup (OSX, tested with node 10, 11, 12).

**Comment by waspeer** [comment]
Same!

**Comment by christiaanwesterbeek** [comment]
Just for good measure, here's the error stack of Atom:

> Uncaught (in promise) NodeError: Callback must be a function
>     at makeCallback (fs.js:165:11)
>     at Object.fs.unlink (fs.js:1048:14)
>     at getTtlGrammarFiles.then.ttlGrammarFiles (/.../.atom/packages/language-babel/lib/create-ttl-grammar.js:260:12)

>   | NodeError | @ | internal/errors.js:157
> -- | -- | -- | --
>   | makeCallback | @ | fs.js:165
>   | fs.unlink | @ | fs.js:1048
>   | getTtlGrammarFiles.then.ttlGrammarFiles | @ | create-ttl-grammar.js? [sm]:271
>   | Promise.catch (async) |   |  
>   | doesGrammarFileExist.then.ifFileExists | @ | create-ttl-grammar.js? [sm]:54
>   | Promise.then (async) |   |  
>   | Promise | @ | create-ttl-grammar.js? [sm]:48
>   | createGrammar | @ | create-ttl-grammar.js? [sm]:46
>   | configChangedTimer.setTimeout | @ | create-ttl-grammar.js? [sm]:222
> 

Related: https://github.com/gruntjs/grunt-contrib-jasmine/issues/266

**Comment by Axedyson** [comment]
The same problem occurs for me when setting the following tagged template grammar:

![Anmærkning 2020-02-14 000454](https://user-images.githubusercontent.com/28491857/74486616-a8713b80-4ebd-11ea-8435-35b6194f4243.jpg)

**Comment by paulobarcelos** [comment]
This is still the case today... super frustrating. Having the same problem on a new mac, fresh installation of Atom and up to date `language-babel` package.

**Comment by Navigatron** [comment]
I am experiencing the same issue. Setting:

```
html:text.html.basic
```

Versions:

![screenshot](https://user-images.githubusercontent.com/6775862/91777103-efeeb900-ebbc-11ea-86eb-5d9b762784a1.png)

**Comment by tiffting** [comment]
> The same problem occurs for me when setting the following tagged template grammar:
> 
> ![Anmærkning 2020-02-14 000454](https://user-images.githubusercontent.com/28491857/74486616-a8713b80-4ebd-11ea-8435-35b6194f4243.jpg)

Experiencing similar issue with `/* @html */:text.html.basic`

**Comment by eminvegan** [comment]
I have the same issue with .mjs files using template literals.
My plugin list is:
atom-beautify
busy-signal
docblockr
file-icons
highlight-selected
hyperclick
ide-css
intentions
language-babel
language-javascript-plus
linter (maybe incompatible?)
linter-eslint (maybe incompatible?)
linter-jshint (maybe incompatible?)
linter-ui-default (maybe incompatible?)
remember-folds
remote-ftp

**Comment by bruns8234** [comment]
Problem still exists since now more than 2 years. Does anybody think it will be solved? I appreciate to get a solution because changing from VS Code to Atom does not get easier with such problems (I code in js and html and want to use this feature as an replacement for the ES6-html Plugin of VS-Code (which marks html in template strings).

**Comment by tinbka** [comment]
Same there since 3 years
