### ISSUE TITLE
Failed to activate the language-babel package

### ISSUE THREAD

**Issue by Nonlimit** [gandm/language-babel#87]
**Atom Version**: 1.0.18
**System**: Windows 8.1
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package, v0.15.3

### Stack Trace

Failed to activate the language-babel package

```
At Cannot find module 'path-is-inside'

Error: Cannot find module 'path-is-inside'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Администратор\AppData\Local\atom\app-1.0.18\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Администратор\.atom\packages\language-babel\lib\transpiler.coffee:3:16)
    at Object.<anonymous> (C:\Users\Администратор\.atom\packages\language-babel\lib\transpiler.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Администратор\AppData\Local\atom\app-1.0.18\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
language-babel, v0.15.3
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by gandm** [comment]
`path-is-inside` is a node js module dependency so it should download as part of the atom package install. 

Is this a new install of language-babel? Did you install via the GUI or CLI?
It should exist in `C:\Users\Администратор\.atom\packages\language-babel\node_modules\path-is-inside` If it doesn't then the package install didn't complete/work. 

If the directory exists you can try `cd \Users\Администратор\.atom\packages\language-babel` and then doing a `apm upgrade`

**Comment by gandm** [comment]
I meant `apm update`!

**Comment by Nonlimit** [comment]
I uninstall Atom Version: 1.0.18 and install Atom version 1.0.10 and error has been gone

**Comment by gandm** [comment]
I presume it's an Atom issue of some sort as I'm not dependent on any version of Atom.
